/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Launch from "./public/game/Launch"
import flight from "./lb/canvas/wnd/flight"
import Bar from "./ll/other/Bar"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1080;
    static height:number=1920;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="res/scenes/Launch.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("public/game/Launch.ts",Launch);
        reg("lb/canvas/wnd/flight.ts",flight);
        reg("ll/other/Bar.ts",Bar);
    }
}
GameConfig.init();